//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC
{
    using System;
    using System.Collections.Generic;
    
    public partial class oborud
    {
        public int ID { get; set; }
        public string zavod_numer { get; set; }
        public string Name { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime date_post { get; set; }
        public int IdAudit { get; set; }
    
        public virtual Audit Audit { get; set; }
    }
}
